import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'

const component = readFileSync('app/components/connect-agent.vue', 'utf8')
const app = readFileSync('app/app.vue', 'utf8')
const docs = readFileSync('docs/CONNECT-AN-AGENT.md', 'utf8')
const responsive = readFileSync('assets/css/mobile-v2.css', 'utf8')
const nuxtConfig = readFileSync('nuxt.config.ts', 'utf8')

assert.match(component, /id="connect-agent"/)
assert.doesNotMatch(component, /https:\/\/kindrobots\.org\/bots/)
assert.doesNotMatch(component, /Create or choose an owned Bot/i)
assert.match(component, /does not need to\s+be a Kind Robots Bot/i)
assert.match(component, /https:\/\/kindrobots\.org\/dashboard#agent-credentials/)
assert.match(component, /profile:read/)
assert.match(component, /forum:read/)
assert.match(component, /forum:write/)
assert.match(component, /RAINBOW_BUTTERFLIES_API_KEY/)
assert.match(component, /\/api\/v1\/profile/)
assert.match(component, /\/api\/v1\/forum\/threads\?channel=introductions&limit=1/)
assert.match(component, /recurring check-in/i)
assert.doesNotMatch(component, /v-model[^>]*(token|secret|apiKey)/i)
assert.doesNotMatch(component, /type="password"/i)

assert.match(app, /<ConnectAgent\s*\/>/)
assert.match(app, /title: 'Join'/)
assert.match(app, /title: 'Explore'/)
assert.match(app, /title: 'Generate'/)
assert.match(app, /title: 'Help'/)
assert.doesNotMatch(app, /Current Mission Work/)
assert.doesNotMatch(app, /Current Experiments/)

assert.match(docs, /Status: transitional v2 onboarding path\./)
assert.match(docs, /does \*\*not\*\* need to be a Kind Robots Bot/)
assert.match(docs, /dashboard#agent-credentials/)
assert.match(docs, /\/api\/v1\/profile/)
assert.match(docs, /RAINBOW_BUTTERFLIES_API_KEY/)
assert.match(docs, /recurring check-in/i)
assert.doesNotMatch(docs, /Create or choose a \*\*Kind Robots Bot\*\*/)
assert.doesNotMatch(docs, /YOUR_AGENT_KEY/)

assert.match(nuxtConfig, /assets\/css\/mobile-v2\.css/)
assert.match(responsive, /\.site-header \.brand span\s*\{\s*display: none/)
assert.match(responsive, /grid-template-columns: auto minmax\(0, 1fr\)/)
assert.match(responsive, /\.gateway-grid/)
assert.match(responsive, /overflow-wrap: anywhere/)

console.log('Rainbow Connect an Agent + v2 gateway contract: OK')
