import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'

const component = readFileSync('app/components/connect-agent.vue', 'utf8')
const app = readFileSync('app/app.vue', 'utf8')
const home = readFileSync('app/pages/index.vue', 'utf8')
const responsive = readFileSync('assets/css/mobile-v2.css', 'utf8')
const nuxtConfig = readFileSync('nuxt.config.ts', 'utf8')

assert.match(component, /id="connect-agent"/)
assert.match(component, /Connect your AI agent\./)
assert.match(component, /href="\/agents"/)
assert.match(component, /href="\/login\?returnTo=%2Fagents"/)
assert.match(component, />Identity</)
assert.match(component, />Permissions</)
assert.match(component, />Check-ins</)
assert.doesNotMatch(component, /kindrobots\.org/i)
assert.doesNotMatch(component, /dashboard#agent-credentials/i)
assert.doesNotMatch(component, /Create or choose an owned Bot/i)
assert.doesNotMatch(component, /Kind Robots Bot/i)
assert.doesNotMatch(component, /RAINBOW_BUTTERFLIES_API_KEY/)
assert.doesNotMatch(component, /curl\s+-H/i)
assert.doesNotMatch(component, /recurring check-in contract/i)
assert.doesNotMatch(component, /v-model[^>]*(token|secret|apiKey)/i)
assert.doesNotMatch(component, /type="password"/i)

assert.match(app, /<NuxtPage\s*\/>/)
assert.match(home, /<ConnectAgent\s*\/>/)
assert.match(home, /title: 'Join'/)
assert.match(home, /title: 'Explore'/)
assert.match(home, /title: 'Generate'/)
assert.match(home, /title: 'Help'/)
assert.doesNotMatch(home, /Current Mission Work/)
assert.doesNotMatch(home, /Current Experiments/)

assert.match(nuxtConfig, /assets\/css\/mobile-v2\.css/)
assert.match(responsive, /\.site-header \.brand span\s*\{\s*display: none/)
assert.match(responsive, /grid-template-columns: auto minmax\(0, 1fr\)/)
assert.match(responsive, /\.gateway-grid/)
assert.match(responsive, /overflow-wrap: anywhere/)

console.log('Rainbow Connect an Agent + v2 gateway contract: OK')
